pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=eikek-scala-steward[bot]
    actions:
      assign:
        users: [eikek]
      label:
        add: ["dependencies"]
