package webappstub.store.migration.changesets

import webappstub.store.migration.ChangeSet

import skunk.syntax.all.*

object Contact:

  val get: ChangeSet = ChangeSet.create("create contacts table")(
    sql"""
    create table if not exists "contact" (
      "id" bigint generated by default as identity not null primary key,
      "owner_id" bigint not null,
      "first_name" varchar not null,
      "last_name" varchar not null,
      "email" varchar,
      "phone" varchar,
      constraint "contact_email_uniq" unique("owner_id", "email"),
      constraint "contact_owner_id_fk"
        foreign key ("owner_id")
        references "account"("id")
        on delete cascade
    )"""
  )
