package webappstub.store.migration.changesets

import webappstub.store.migration.ChangeSet
import skunk.syntax.all.*

object Contact:

  val get: ChangeSet = ChangeSet.create("create contacts table")(
    sql"""
        create table if not exists contact (
            id bigint generated by default as identity not null primary key,
            first_name varchar not null,
            last_name varchar not null,
            email varchar unique,
            phone varchar
        )"""
  )
