name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 100
          fetch-tags: true

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: sbt ci ${{ github.ref }}
        run: nix develop .#ci --command mill --no-server ci
  ci:
    runs-on: ubuntu-latest
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
